version: "3.9"
networks:
  spring-demo-project_default:
    driver: bridge

services:
  database-mysql8:
    image: mysql:8.0.36
    container_name: database-mysql8
    environment:
      MYSQL_DATABASE: database-mysql8
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 11802:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
    networks:
      - spring-demo-project_default