### 게시글 작성
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title": "blog title",
  "postContent": "blog postContent"
}

### 모든 게시글 조회
GET http://localhost:8080/api/articles
Content-Type: application/json

### 단일 게시글 조회
@id=1
GET http://localhost:8080/api/articles/{{id}}
Content-Type: application/json

### 게시글 삭제
DELETE http://localhost:8080/api/articles/{{id}}

### 게시글 수정
PUT http://localhost:8080/api/articles/{{id}}
Content-Type: application/json

{
  "title": "updated title",
  "postContent": "updated postContent"
}

###