### 댓글 정보 생성
@articleId = 2
POST http://localhost:8080/api/articles/{{articleId}}/comments
Content-Type: application/json

{
  "body": "댓글 내용1"
}

### 댓글 정보 조회
@commentId = 7
GET http://localhost:8080/api/comments/{{commentId}}

### 댓글 정보 수정
PUT http://localhost:8080/api/comments/{{commentId}}
Content-Type: application/json

{
  "body": "댓글 내용1"
}

### 댓글 정보 삭제
@removeCommentId = 7
DELETE http://localhost:8080/api/comments/{{removeCommentId}}

### 게시글/댓글 조회
GET http://localhost:8080/api/articles/{{articleId}}/comments